// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {wifi} from '../models';

export function GetScannerConfig():Promise<models.ScannerConfig>;

export function GetTopology():Promise<models.ScanResult>;

export function ScanWifi():Promise<Array<wifi.Network>>;

export function UpdateScannerConfig(arg1:models.ScannerConfig):Promise<void>;
