// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScannerConfig() {
  return window['go']['main']['App']['GetScannerConfig']();
}

export function GetTopology() {
  return window['go']['main']['App']['GetTopology']();
}

export function ScanWifi() {
  return window['go']['main']['App']['ScanWifi']();
}

export function UpdateScannerConfig(arg1) {
  return window['go']['main']['App']['UpdateScannerConfig'](arg1);
}
